openapi: 3.0.3
info:
  title: search API
  description: |-
    This is a super simple API for searching on mentorhub
  contact:
    email: devs@agile-learning.institute
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
paths:
  /api/health/:
    get:
      summary: Opensearch health endpoint
      operationId: getHealth
      parameters:
      - name: level
        in: query
        description: "The level of awareness attributes (e.g. /api/health?level=awareness_attributes)"
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
  api/config/:
    get:
      summary: Get API Configuration Information
      operationId: getConfig
      parameters:
        - name: flat_settings
          in: query
          description: "Whether to return settings in flat form."
          required: false
          schema:
            type: boolean
        - name: include_defaults
          in: query
          description: "Whether to include default settings."
          required: false
          schema:
            type: boolean
        - name: cluster_manager_timeout
          in: query
          description: "The amount of time to wait for a resposne form the cluster manager node. Default is 30 seconds."
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    Health:
      type: object
      properties:
          clusterName:
            description: "The name of the cluster."
            type: string
          status:
            description: "The cluster health status, which represents the state of shard allocation in the cluster. May be green, yellow, or red."
            type: string
          numberOfNodes:
            description: "The number of nodes in the cluster."
            type: integer
          numberOfDataNodes: 
            description: "The number of data nodes in the cluster."
            type: integer
          discoveredClusterManager:
            description: "Specifies whether the cluster manager is discovered."
            type: boolean
          activePrimaryShards:
            description: "The number of active primary shards."
            type: integer
          activeShards:
            description: "The total number of active shards, including primary and replica shards."
            type: integer
          relocatingShards:
            description: "The number of relocating shards."
            type: integer
          initializingShards:
            description: "The number of initializing shards."
            type: integer
          unassignedShards:
            description: "The number of unassigned shards."
            type: integer
          delayedUnassignedShards:
            description: "The number of delayed unassigned shards."
            type: integer
          numberOfPendingTasks:
            description: "The number of pending tasks in the cluster."
            type: integer
          numberOfInFlightFetch:
            description: "The number of unfinished fetches."
            type: integer
          taskMaxWaitingInQueueMillis:
            description: "The maximum wait time for all tasks waiting to be performed, in milliseconds."
            type: integer
          activeShardsPercentAsNumber:
            description: "The percentage of active shards in the cluster."
            type: number
          awarenessAttributes:
            description: "Contains cluster health information for each awareness attribute."
            type: object
            properties:
              active_shards:
                type: integer
              initializing_shards:
                type: integer
              relocating_shards:
                type: integer
              unassigned_shards:
                type: integer
              data_nodes:
                type: integer
              weight:
                type: integer
